name: where_in_the_law
description: "A Flutter app to find Ghanaian laws easily."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_animations: ^1.0.0
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.0.0
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.2
  firebase_analytics: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/law_data.json
    - assets/game_questions.json
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf


# Flutter Launcher Icons configuration (moved to root level)
flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
  macos: 
    generate: true
  linux:
    generate: true
  web:
    generate: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true


